Repository cyber-shuttle/mcp-server, pull requests merged in 2025-07, with the labels that each got.

#5 Update README.md with new project structure
  README.md
Labels: documentation

#7 Testing MCP server with OpenAI Agent
  demos/cybershuttle_openai_demo.py
Labels: enhancement

#8 Script for testing v1 of the MCP Server
  tests/test_cybershuttle_mcp.py
Labels: enhancement

#10 Update cybershuttle.yml
  cybershuttle.yml
Labels: documentation

#16 Make resource_type to UPPERCASE
  src/cybershuttle_mcp_server.py
Labels: bug

#18 Debugging /api/v1/rf/resources/public/tags/all endpoint
  src/cybershuttle_auth.py
  src/cybershuttle_mcp_server.py
Labels: bug, documentation

#22 Add debugging logs
  src/cybershuttle_mcp_server.py
Labels: bug

#21 fix resources/tags route
  src/cybershuttle_mcp_server.py
Labels: bug

#23 Update parameters and improve comments and overall structure
  demos/cybershuttle_openai_demo.py
  src/cybershuttle_mcp_server.py
Labels: documentation

#26 Added semantic searching capabilities to AI Agent, and fixed search/ endpoint bugs
  demos/cybershuttle_openai_demo.py
  src/cybershuttle_mcp_server.py
Labels: bug, enhancement

#29 Updates to LangChain Agent tools
  demos/langchain_qwen_demo.py
  src/cybershuttle_mcp_server.py
Labels: enhancement

#30 Update .gitignore to ignore pycache files
  .gitignore
Labels: documentation

#31 Create HTTP API server for the LangChain agent. Exposing it to the Re…
  demos/langchain_api_server.py
  demos/langchain_qwen_demo.py
Labels: enhancement

#33 Cleaning up search queries from Qwen3 agent
  demos/langchain_qwen_demo.py
Labels: enhancement
